### ISSUE TITLE
Example app build linking error on MacOS Sonoma 14.7 M2 Pro chip

### ISSUE THREAD

**Issue by david-montiel-t** [prisms-center/phaseField#377]
The following linking error occurs when compiling a PRISMS-PF application with AppleClang 16.0.0.16000026 compiler, using deal.II 9.5.2 on MacOS Sonoma 14.7 with M2 Pro chip:

ld: symbol(s) not found for architecture arm64
c++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [main-debug] Error 1
make[1]: *** [CMakeFiles/main_debug.dir/all] Error 2
make: *** [all] Error 2

No issues if we compile with GNU 9.4.0 using deal.II 9.5.0.

Also no issues if we compile with previous CMakeLists.txt versions (tag [v2.4](https://github.com/prisms-center/phaseField/tree/v2.4)).

**Comment by landinjm** [comment]
Can you compile with `make VERBOSE=1`

**Comment by david-montiel-t** [comment]
See file below:

[make_output.log](https://github.com/user-attachments/files/18307731/make_output.log)
